USE wonderland_elections;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Casted_Vote;
DROP TABLE IF EXISTS Ballot;
DROP TABLE IF EXISTS Voting_Registry;
DROP TABLE IF EXISTS Voting_Center;
DROP TABLE IF EXISTS Elections_Staff;
DROP TABLE IF EXISTS Folks;
DROP TABLE IF EXISTS Places;
SET FOREIGN_KEY_CHECKS = 1;